#!/usr/bin/env python2
#
#
# Free for any use, there are no restrictions
#
# This just "dumps" the data to the standard output
#
# TODO: Make this a more generic export utilty, exporting to files other
# programs can import (i.e. CSV and the like).
#
# Usage: $0 [FILE]

from __future__ import print_function
import sys
from operapass import opwand

if __name__ == "__main__":
    pwfile = opwand.GetPasswordfile()
    passwords=opwand.getData(pwfile)
    opwand.PrintTextData(passwords)

    print("total of",len(passwords),"password areas")
    print("wand.dat file:",pwfile)
